/*!
* SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2013 SAP SE. All rights reserved
* @deprecated since SAPUI 5 version 1.28.0
*/
jQuery.sap.declare("sap.suite.ui.smartbusiness.drilldown.lib.CustomTable");sap.m.Table.extend("sap.suite.ui.smartbusiness.drilldown.lib.CustomTable",{metadata:{properties:{actionItems:{type:"any",multiple:true}}},renderer:{}});
sap.suite.ui.smartbusiness.drilldown.lib.CustomTable.prototype.init=function(){sap.m.Table.prototype.init.apply(this);this._selectedContext=[];var c=new sap.m.Bar({contentMiddle:[new sap.m.Label({text:"{i18n>TABLE_POPOVER_HEADING}"})],contentRight:(jQuery.device.is.phone)?[]:[new sap.m.Button({icon:"sap-icon://decline",width:"2.375rem",press:jQuery.proxy(this._closePopover,this)})]});this._popOver=new sap.m.ResponsivePopover({modal:false,enableScrolling:true,verticalScrolling:true,horizontalScrolling:false,placement:sap.m.PlacementType.Auto,contentWidth:"18rem",customHeader:c}).addStyleClass("smartbusinessTablePopover");var s=sap.ui.getCore().getUIArea(sap.ui.getCore().getStaticAreaRef());s.addContent(this._popOver,true);};
sap.suite.ui.smartbusiness.drilldown.lib.CustomTable.prototype._closePopover=function(){if(this._popOver.isOpen()){this._popOver.close();}};
sap.suite.ui.smartbusiness.drilldown.lib.CustomTable.prototype.setPopoverFooter=function(c){this._popOver.removeAllContent();this._popOver.addContent(c);};
sap.suite.ui.smartbusiness.drilldown.lib.CustomTable.prototype.onBeforeRendering=function(){this._popOver.getCustomHeader().getContentMiddle()[0].setText(this.getModel("i18n").getProperty("TABLE_POPOVER_HEADING"));this.attachItemPress(function(e){var a=e.getParameters().listItem||e.getParameters().listItems[0];this.popoverOpenAt=a;var s=[];var i=this.getSelectedItems();var c=this.getColumns();if(i.length){var b=i[0];var d=b.getBindingContext().getObject();var o={};for(var f in d){o[f]=d[f];}s.push(o);this.setSelectedContext(s);if(true||this._notEmpty()){this._popOver.openBy(a.getCells()[parseInt(a.getCells().length/2)||0],false);}}else{this._closePopover();}});};
sap.suite.ui.smartbusiness.drilldown.lib.CustomTable.prototype._notEmpty=function(){var c=this._popOver.getContent();var n=false;if(c&&c.length>0){var b=c[0];var l=b.getItems();l.forEach(function(a){if(a.getItems().length>0){n=true;return false;}});}return n;};
sap.suite.ui.smartbusiness.drilldown.lib.CustomTable.prototype.setSelectedContext=function(s){this._selectedContext=s;};
sap.suite.ui.smartbusiness.drilldown.lib.CustomTable.prototype.getSelectedContext=function(s){return this._selectedContext;};
