/*!
* SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2013 SAP SE. All rights reserved
* @deprecated since SAPUI 5 version 1.28.0
*/
jQuery.sap.declare("sap.suite.ui.smartbusiness.tiles.Comparison");jQuery.sap.require("sap.suite.ui.smartbusiness.tiles.Generic");sap.suite.ui.smartbusiness.tiles.Generic.extend("sap.suite.ui.smartbusiness.tiles.Comparison",{metadata:{properties:{kpiValueRequired:{type:"boolean",defaultValue:false},tileType:{type:"string",defaultValue:"CT"}}},renderer:{}});
sap.suite.ui.smartbusiness.tiles.Comparison.prototype.init=function(){sap.suite.ui.smartbusiness.tiles.Generic.prototype.init.apply(this);this.setAggregation("_tile",new sap.suite.ui.commons.GenericTile({header:"{/header}",subheader:"{/subheader}",size:this.getSize(),frameType:this.getFrameType(),tileContent:new sap.suite.ui.commons.TileContent({unit:"{/unit}",size:this.getSize(),footer:"{/footerNum}",content:new sap.suite.ui.commons.ComparisonChart({scale:"{/scale}",size:this.getSize(),state:"{/state}",data:{template:new sap.suite.ui.commons.ComparisonData({title:"{title}",value:"{value}",color:"{color}",displayValue:"{displayValue}"}),path:"/data"}})}),press:jQuery.proxy(this.tilePressed,this)}));this.jsonModel=new sap.ui.model.json.JSONModel();this.setModel(this.jsonModel);};
sap.suite.ui.smartbusiness.tiles.Comparison.prototype.onBeforeRendering=function(){sap.suite.ui.smartbusiness.tiles.Generic.prototype.onBeforeRendering.apply(this);if(this.getContentOnly()){this.setAggregation("_tile",new sap.suite.ui.commons.TileContent({unit:"{/unit}",size:this.getSize(),footer:"{/footerNum}",content:new sap.suite.ui.commons.ComparisonChart({scale:"{/scale}",size:this.getSize(),state:"{/state}",data:{template:new sap.suite.ui.commons.ComparisonData({title:"{title}",value:"{value}",color:"{color}",displayValue:"{displayValue}"}),path:"/data"}})}));}};
sap.suite.ui.smartbusiness.tiles.Comparison.prototype.doProcess=function(){var t=this;this._fetchDataForComparisonTile(function(k){var d={};d.data=k.kpiData;if(k.unitPrefix){d.unit=k.unitPrefix;}if(true||t.isAssociatedKpi()){d.subheader=this.evaluationApi.getTitle();d.header=this.evaluationApi.getKpiName();}t.jsonModel.setData(d);t.setDoneState();},this.logError);};
sap.suite.ui.smartbusiness.tiles.Comparison.prototype._fetchDataForComparisonTile=function(s,e){var _=function(a){var b=[{name:this.EVALUATION_DATA.COLUMN_NAME,order:"desc"}];if(a&&a.SORTING){var c=a.SORTING;if((c.order=='asc'||c.order=='desc')&&(c.by=='M'||c.by=='D')){var r=[];r.push({name:(c.by=='M'?this.evaluationApi.getKpiMeasureName():this.getDimension()),order:c.order});return r;}}return b;};var t=this;var p={};this.oConfig=this.EVALUATION_DATA;p.serviceUri=this._addSystemAliasToUri(this.evaluationApi.getODataUrl(),this.getSapSystem());p.entitySet=this.evaluationApi.getEntitySet();p.measure=this.evaluationApi.getKpiMeasureName();p.dimension=this.getDimension();p.filter=this.getAllFilters();p.sort=_.apply(this,[this.getTileConfiguration()]);p.dataLimit=3;t.oConfig.FINALVALUE={};p.sortingColumn=this.evaluationApi.getKpiMeasureName();var f=sap.suite.ui.smartbusiness.lib.Util.odata.getUri(p);var u=this.UOM_PROPERTY_MAPPING[this.evaluationApi.getKpiMeasureName()];var d=this.TEXT_PROPERTY_MAPPING;this.comparisionChartODataRef=f.model.read(f.uri,null,null,true,function(a){if(a&&a.results&&a.results.length){if(u){t.oConfig.FINALVALUE.unitPrefix=a.results[0][u];}t.oConfig.FINALVALUE.kpiData=a;p.dimension=d[t.getDimension()];t.oConfig.FINALVALUE.kpiData=t._processDataForComparisonChart(t.oConfig.FINALVALUE.kpiData,p.measure,p.dimension);s.call(t,t.oConfig.FINALVALUE);t.initCTPopup();}else{t.setNoData();}},function(a){if(a&&a.response){jQuery.sap.log.error(a.message+" : "+a.request.requestUri);}});};
sap.suite.ui.smartbusiness.tiles.Comparison.prototype._processDataForComparisonChart=function(d,m,a){var b=true;var t=this.getTileConfiguration();var s=(t&&t.SORTING&&t.SORTING.dimension_color)||(function(){b=false;return sap.suite.ui.commons.ValueStatus.Neutral;})();var f=[];var c;var g=this;if(!b){jQuery.sap.log.error("No Tile Configuration available for tile - "+this.getId());}for(var i=0;i<d.results.length;i++){var h=d.results[i];var j={};try{j.title=h[a].toString();}catch(e){j.title="";};j.value=Number(h[m]);var k=Number(h[m]);var l=this.isACurrencyMeasure(m);var u=this.oConfig.FINALVALUE.unitPrefix;var c=this.libFormat(k,l,u);j.displayValue=c.toString();if(s==void(0)){j.color=sap.suite.ui.commons.ValueStatus.Neutral;}else{j.color=s;}f.push(j);}return f;};
sap.suite.ui.smartbusiness.tiles.Comparison.prototype.doDummyProcess=function(){this.jsonModel.setData(this.getDummyDataForComparisonTile());};
sap.suite.ui.smartbusiness.tiles.Comparison.prototype.showCTPopup=function(){this._CTpopOver.openBy(this);};
sap.suite.ui.smartbusiness.tiles.Comparison.prototype.initCTPopup=function(){var s=this;var m=new sap.ui.model.json.JSONModel();var a={"THRESHOLDS":[]};var l=new sap.ui.core.Locale(sap.ui.getCore().getConfiguration().getLanguage());jQuery.sap.require("sap.ui.core.format.NumberFormat");this.VALUE_FORMATTER=sap.ui.core.format.NumberFormat.getFloatInstance({style:"standard"},l);var t=new sap.m.List({});var g=function(f){return{"Error":sap.ui.core.ValueState.Error,"Neutral":sap.ui.core.ValueState.None,"Good":sap.ui.core.ValueState.Success,"Warning":sap.ui.core.ValueState.Warning,"Critical":sap.ui.core.ValueState.Warning}[f]||sap.ui.core.ValueState.None;};t.bindItems("/THRESHOLDS",new sap.m.ObjectListItem({title:"{name}",number:"{value}",numberState:{path:"color",formatter:g}}));t.setModel(m);var b=this.oConfig.FINALVALUE.kpiData;if(this.evaluationApi.getScaling()==-2){for(var e in b){if(b[e]){b[e].value=(b[e].value*100)+" %";}}}for(var j in b){a.THRESHOLDS.push({name:b[j].title,value:this.VALUE_FORMATTER.format(b[j].value),color:b[j].color});}m.setData(a);var d=this.TEXT_PROPERTY_MAPPING[this.getDimension()]||this.getDimension();var c=new sap.m.Bar({contentMiddle:[new sap.m.Label({text:d})],contentRight:(jQuery.device.is.phone)?[]:[new sap.m.Button({icon:"sap-icon://decline",width:"2.375rem",press:jQuery.proxy(function(){if(this._CTpopOver.isOpen()){this._CTpopOver.close();}},this)})]});this._CTpopOver=new sap.m.ResponsivePopover({modal:false,enableScrolling:true,verticalScrolling:true,horizontalScrolling:false,placement:sap.m.PlacementType.Auto,contentWidth:"18rem",customHeader:c,content:[t]});var S=sap.ui.getCore().getUIArea(sap.ui.getCore().getStaticAreaRef());S.addContent(this._CTpopOver,true);};
