/*!
* SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2013 SAP SE. All rights reserved
* @deprecated since SAPUI 5 version 1.28.0
*/
jQuery.sap.declare("sap.suite.ui.smartbusiness.tiles.HarveyBall");jQuery.sap.require("sap.suite.ui.smartbusiness.tiles.Generic");sap.suite.ui.smartbusiness.tiles.Generic.extend("sap.suite.ui.smartbusiness.tiles.HarveyBall",{metadata:{properties:{kpiValueRequired:{type:"boolean",defaultValue:true},tileType:{type:"string",defaultValue:"CM"},size:{type:"string",defaultValue:"S"},}},renderer:{}});
sap.suite.ui.smartbusiness.tiles.HarveyBall.prototype.init=function(){sap.suite.ui.smartbusiness.tiles.Generic.prototype.init.apply(this);this._bShowUOM=false;this._bUseFormattedVDMValue=false;this._bShowKpiMeasureUOMInFooter=true;this._bHasKpiMeasure=null;this._oDataRequestReference={};this.setAggregation("_tile",new sap.suite.ui.commons.GenericTile({header:"{/header}",subheader:"{/subheader}",size:this.getSize(),frameType:this.getFrameType(),tileContent:new sap.suite.ui.commons.TileContent({size:"S",content:new sap.suite.ui.commons.HarveyBallMicroChart({total:"{/totalValue}",size:"S",items:[new sap.suite.ui.commons.HarveyBallMicroChartItem({fraction:"{/fractionValue}",color:"{/color}"})]})}),press:jQuery.proxy(this.tilePressed,this)}));this.jsonModel=new sap.ui.model.json.JSONModel();this.setModel(this.jsonModel);};
sap.suite.ui.smartbusiness.tiles.HarveyBall.prototype.onBeforeRendering=function(){sap.suite.ui.smartbusiness.tiles.Generic.prototype.onBeforeRendering.apply(this);if(this.getContentOnly()){this.setAggregation("_tile",new sap.suite.ui.commons.TileContent({size:"S",content:new sap.suite.ui.commons.HarveyBallMicroChart({total:"{/totalValue}",size:"S",items:[new sap.suite.ui.commons.HarveyBallMicroChartItem({fraction:"{/fractionValue}",color:"{/color}"})]})}));}};
sap.suite.ui.smartbusiness.tiles.HarveyBall.prototype._getTrendColor=function(){var r=null;var w=window.parseFloat(this.WARNING_LOW_VALUE);var c=window.parseFloat(this.CRITICAL_LOW_VALUE);var a=window.parseFloat(this.CRITICAL_HIGH_VALUE);var b=window.parseFloat(this.WARNING_HIGH_VALUE);var i=this.EVALUATION_DATA.GOAL_TYPE;if(this.evaluationApi.isMinimizingKpi()){if(this.hasSomeValue(a,b)){if(this.KPI_VALUE<b){r=sap.suite.ui.commons.InfoTileValueColor.Good;}else if(this.KPI_VALUE<=a){r=sap.suite.ui.commons.InfoTileValueColor.Critical;}else{r=sap.suite.ui.commons.InfoTileValueColor.Error;}}}else if(this.evaluationApi.isMaximizingKpi()){if(this.hasSomeValue(c,w)){if(this.KPI_VALUE<c){r=sap.suite.ui.commons.InfoTileValueColor.Error;}else if(this.KPI_VALUE<=w){r=sap.suite.ui.commons.InfoTileValueColor.Critical;}else{r=sap.suite.ui.commons.InfoTileValueColor.Good;}}}else{if(this.hasSomeValue(w,b,c,a)){if(this.KPI_VALUE<c||this.KPI_VALUE>a){r=sap.suite.ui.commons.InfoTileValueColor.Error;}else if((this.KPI_VALUE>=c&&this.KPI_VALUE<=w)||(this.KPI_VALUE>=b&&this.KPI_VALUE<=a)){r=sap.suite.ui.commons.InfoTileValueColor.Critical;}else{r=sap.suite.ui.commons.InfoTileValueColor.Good;}}}return r;};
sap.suite.ui.smartbusiness.tiles.HarveyBall.prototype.doProcess=function(){var t=this;this._fetchDataForHarveyBallTile(function(d){var i=this.isACurrencyMeasure(this.getVariable("totalMeasure"));var a=this.isACurrencyMeasure(this.getVariable("fractionMeasure"));var j={totalValue:Number(d.totalValue),totalValueLabel:this.libFormat(Number(d.totalValue),i,d.totalValueUnit)+" "+d.totalValueUnit,fractionValue:Number(d.fractionValue),fractionValueLabel:this.libFormat(Number(d.fractionValue),a,d.fractionValueUnit)+" "+d.fractionValueUnit};if(t.getTileConfiguration().IS_HARVEY_FRACTION_KPIMEASURE){j.color=t._getTrendColor();}if(true||t.isAssociatedKpi()){j.subheader=this.evaluationApi.getTitle();j.header=this.evaluationApi.getKpiName();}if(this._bShowKpiMeasureUOMInFooter&&this._bHasKpiMeasure){}t.jsonModel.setData(j);t.setDoneState();t.initPopup();},this.logError);};
sap.suite.ui.smartbusiness.tiles.HarveyBall.prototype._getFormattedHarveyFilters=function(h){var t=[];if(h&&h[0]&&h[0].VALUE_1){h[0].VALUE_1.forEach(function(c){harveyFilters.push({NAME:h[0].NAME,TYPE:"FI",VALUE_1:[c],OPERATOR:tileConfiguration.HARVEY_FILTERS[0].OPERATOR,VALUE_2:[]})})}if(tileConfiguration.HARVEY_FILTERS[0]&&tileConfiguration.HARVEY_FILTERS[0].VALUE_1){}};
sap.suite.ui.smartbusiness.tiles.HarveyBall.prototype._fetchDataForHarveyBallTile=function(s,e){function m(M,u,b,c,S,E){var d=t.UOM_PROPERTY_MAPPING[b];var D=M.read(u,null,null,true,function(f){t.deregisterODataRequest(c);if(f&&f.results&&f.results.length){k[c]=f.results[0][b];k[c+"Unit"]=f.results[0][d]||"";S.call(t,k);}else{E.call(t,"no Response from QueryServiceUri");}},function(f){t.deregisterODataRequest(c);if(f&&f.response){jQuery.sap.log.error(f.message+" : "+f.request.requestUri);}});t.registerODataRequest(c,D);}var t=this;var a=this.getTileConfiguration();this._bHasKpiMeasure=true;var q;var k={};var h=[];var v;var p={serviceUri:this._addSystemAliasToUri(this.evaluationApi.getODataUrl(),this.getSapSystem()),entitySet:this.evaluationApi.getEntitySet(),measure:this.evaluationApi.getKpiMeasureName(),filter:this.getAllFilters()};if(a.IS_HARVEY_FRACTION_KPIMEASURE){p.measure=a.HARVEY_TOTAL_MEASURE;k.fractionValue=this.KPI_VALUE;k.fractionValueUnit=this.UOM;v="totalValue";}else{a.HARVEY_FILTERS=a.HARVEY_FILTERS||[];k.totalValue=this.KPI_VALUE;k.totalValueUnit=this.UOM;p.filter=p.filter.concat(h);v="fractionValue";}this.setVariable('fractionMeasure',this.evaluationApi.getKpiMeasureName());this.setVariable('totalMeasure',p.measure);q=sap.suite.ui.smartbusiness.lib.Util.odata.getUri(p);m(q.model,q.uri,p.measure,v,s,e);};
sap.suite.ui.smartbusiness.tiles.HarveyBall.prototype.doDummyProcess=function(){this.jsonModel.setData(this.getDummyData());};
sap.suite.ui.smartbusiness.tiles.HarveyBall.prototype.getDummyData=function(){return this._cleanUpDummyData({subheader:"Expenses by Region",header:"Comparative Annual Totals",footerNum:"",footerComp:"",scale:"M",unit:"EUR",fractionValue:34,totalValue:100,size:"S",color:"Good",});};
sap.suite.ui.smartbusiness.tiles.HarveyBall.prototype.showPopup=function(){this._popover.openBy(this);};
sap.suite.ui.smartbusiness.tiles.HarveyBall.prototype.initPopup=function(){var s=this;var m=new sap.ui.model.json.JSONModel();var a={"THRESHOLDS":[]};var l=new sap.ui.core.Locale(sap.ui.getCore().getConfiguration().getLanguage());jQuery.sap.require("sap.ui.core.format.NumberFormat");this.VALUE_FORMATTER=sap.ui.core.format.NumberFormat.getFloatInstance({style:"standard"},l);var t=new sap.m.List({});var g=function(d){return{"Error":sap.ui.core.ValueState.Error,"Neutral":sap.ui.core.ValueState.None,"Good":sap.ui.core.ValueState.Success,"Warning":sap.ui.core.ValueState.Warning,"Critical":sap.ui.core.ValueState.Warning}[d]||sap.ui.core.ValueState.None;};t.bindItems("/THRESHOLDS",new sap.m.ObjectListItem({title:"{name}",number:"{value}",numberState:{path:"color",formatter:g}}));t.setModel(m);var b=this.jsonModel.getData().data;if(this.evaluationApi.getScaling()==-2){for(var e in b){if(b[e]){b[e].value=(b[e].value*100)+" %";}}}for(var j in b){a.THRESHOLDS.push({name:b[j].title,value:this.VALUE_FORMATTER.format(b[j].value),color:b[j].color});}m.setData(a);var c=new sap.m.Bar({contentMiddle:[new sap.m.Label({text:this.getModel("i18n").getProperty("DETAILS")})],contentRight:(jQuery.device.is.phone)?[]:[new sap.m.Button({icon:"sap-icon://decline",width:"2.375rem",press:jQuery.proxy(function(){if(this._popover.isOpen()){this._popover.close();}},this)})]});this._popover=new sap.m.ResponsivePopover({modal:false,enableScrolling:true,verticalScrolling:true,horizontalScrolling:false,placement:sap.m.PlacementType.Auto,contentWidth:"18rem",customHeader:c,content:[t]});var S=sap.ui.getCore().getUIArea(sap.ui.getCore().getStaticAreaRef());S.addContent(this._popover,true);};
sap.suite.ui.smartbusiness.tiles.HarveyBall.prototype.registerODataRequest=function(k,r){this._oDataRequestReference[k]=r;};
sap.suite.ui.smartbusiness.tiles.HarveyBall.prototype.deregisterODataRequest=function(k){delete this._oDataRequestReference[k];};
sap.suite.ui.smartbusiness.tiles.HarveyBall.prototype.abortODataCalls=function(){for(var e in this._oDataRequestReference){this._oDataRequestReference[e].abort();this.deregisterODataRequest(e);}};
