/*!
* SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2013 SAP SE. All rights reserved
* @deprecated since SAPUI 5 version 1.28.0
*/
jQuery.sap.declare("sap.suite.ui.smartbusiness.tiles.MeasureComparison");jQuery.sap.require("sap.suite.ui.smartbusiness.tiles.Generic");sap.suite.ui.smartbusiness.tiles.Generic.extend("sap.suite.ui.smartbusiness.tiles.MeasureComparison",{metadata:{properties:{kpiValueRequired:{type:"boolean",defaultValue:false},tileType:{type:"string",defaultValue:"CM"}}},renderer:{}});
sap.suite.ui.smartbusiness.tiles.MeasureComparison.prototype.init=function(){sap.suite.ui.smartbusiness.tiles.Generic.prototype.init.apply(this);this._bShowUOM=false;this._bUseFormattedVDMValue=false;this._bShowKpiMeasureUOMInFooter=true;this._bHasKpiMeasure=null;this.setAggregation("_tile",new sap.suite.ui.commons.GenericTile({header:"{/header}",subheader:"{/subheader}",size:this.getSize(),frameType:this.getFrameType(),tileContent:new sap.suite.ui.commons.TileContent({unit:"{/unit}",size:this.getSize(),footer:"{/footerNum}",content:new sap.suite.ui.commons.ComparisonChart({scale:"{/scale}",size:this.getSize(),state:"{/state}",data:{template:new sap.suite.ui.commons.ComparisonData({title:"{title}",value:"{value}",color:"{color}",displayValue:"{displayValue}"}),path:"/data"}})}),press:jQuery.proxy(this.tilePressed,this)}));this.jsonModel=new sap.ui.model.json.JSONModel();this.setModel(this.jsonModel);};
sap.suite.ui.smartbusiness.tiles.MeasureComparison.prototype.onBeforeRendering=function(){sap.suite.ui.smartbusiness.tiles.Generic.prototype.onBeforeRendering.apply(this);if(this.getContentOnly()){this.setAggregation("_tile",new sap.suite.ui.commons.TileContent({unit:"{/unit}",size:this.getSize(),footer:"{/footerNum}",content:new sap.suite.ui.commons.ComparisonChart({scale:"{/scale}",size:this.getSize(),state:"{/state}",data:{template:new sap.suite.ui.commons.ComparisonData({title:"{title}",value:"{value}",color:"{color}",displayValue:"{displayValue}"}),path:"/data"}})}));}};
sap.suite.ui.smartbusiness.tiles.MeasureComparison.prototype.doProcess=function(){var t=this;this._fetchDataForMeasureComparisonTile(function(c){var j={};this._processedComparisionData=this._processMeasureComparisionData(c);j.data=this._processedComparisionData;if(true||t.isAssociatedKpi()){j.subheader=this.evaluationApi.getTitle();j.header=this.evaluationApi.getKpiName();}if(this._bShowKpiMeasureUOMInFooter&&this._bHasKpiMeasure){var k=this.UOM_PROPERTY_MAPPING[this.evaluationApi.getKpiMeasureName()];if(k){j.unit=c[k];}}t.jsonModel.setData(j);t.setDoneState();t.initCMPopup();},this.logError);};
sap.suite.ui.smartbusiness.tiles.MeasureComparison.prototype._fetchDataForMeasureComparisonTile=function(s,e){var t=this;var _=function(a){var m=[];if(a&&a.MEASURES&&a.MEASURES.length){var b=a.MEASURES;for(var i=0,l=b.length;i<l;i++){m.push(b[i].name);}}if(m.length){return m;}else{throw new Error("No Measures Defined for Measure Comparision Tile");}};function c(d,a){var b=false;if(d&&d.results&&d.results.length){for(var i=0,l=a.length;i<l&&!b;i++){b=d.results[0][a[i]]!==null;}}return b;}var p={};p.serviceUri=this._addSystemAliasToUri(this.evaluationApi.getODataUrl(),this.getSapSystem());p.entitySet=this.evaluationApi.getEntitySet();p.measure=_(this.getTileConfiguration());if(p.measure.indexOf(this.evaluationApi.getKpiMeasureName())>-1){this._bHasKpiMeasure=true;}p.filter=this.getAllFilters();var f=sap.suite.ui.smartbusiness.lib.Util.odata.getUri(p);this.comparisionChartODataRef=f.model.read(f.uri,null,null,true,function(d){if(c(d,p.measure)){s.call(t,d.results[0]);}else{t.setNoData();}},function(a){if(a&&a.response){jQuery.sap.log.error(a.message+" : "+a.request.requestUri);}});};
sap.suite.ui.smartbusiness.tiles.MeasureComparison.prototype._processMeasureComparisionData=function(r){var p=[],f,V,U,m,a,i,b,o;b=this.getTileConfiguration().MEASURES;for(i=0,l=b.length;i<l;i++){o={};a=b[i].name;m=this.LABEL_PROPERTY_MAPPING[a];o["title"]=m;U=this.UOM_PROPERTY_MAPPING[a];V=this.TEXT_PROPERTY_MAPPING[a];var c=Number(r[a]);if(this._bUseFormattedVDMValue&&V&&(V!=a)){f=r[V];}else{var d=this.isACurrencyMeasure(a);var u=null;var e=false;var k=this.evaluationApi.getKpiMeasureName();var t=this._getOtherThresholdMeasures();if(a===k){e=true;}else if(t){for(var g in t){if(t[g]===a){e=true;}}}if(d){var h=this.UOM_PROPERTY_MAPPING[this.evaluationApi.getKpiMeasureName()];if(h){u=r[h];}}f=this.libFormat(c,d,u);if(this.evaluationApi.getScaling()==-2){if(e){f=this.libFormat(c,d,null,true);}else{f=this.libFormat(c,d);}}}o.value=Number(r[a]);o.displayValue=""+f;if(this._bShowUOM&&U){o.displayValue+=" "+r[U];}o.color=b[i].color;p.push(o);}return p;};
sap.suite.ui.smartbusiness.tiles.MeasureComparison.prototype.doDummyProcess=function(){this.jsonModel.setData(this.getDummyDataForMeasureComparisonTile());};
sap.suite.ui.smartbusiness.tiles.MeasureComparison.prototype.showCMPopup=function(){this._CTpopOver.openBy(this);};
sap.suite.ui.smartbusiness.tiles.MeasureComparison.prototype.initCMPopup=function(){var s=this;var m=new sap.ui.model.json.JSONModel();var a={"THRESHOLDS":[]};var l=new sap.ui.core.Locale(sap.ui.getCore().getConfiguration().getLanguage());jQuery.sap.require("sap.ui.core.format.NumberFormat");this.VALUE_FORMATTER=sap.ui.core.format.NumberFormat.getFloatInstance({style:"standard"},l);var t=new sap.m.List({});var g=function(d){return{"Error":sap.ui.core.ValueState.Error,"Neutral":sap.ui.core.ValueState.None,"Good":sap.ui.core.ValueState.Success,"Warning":sap.ui.core.ValueState.Warning,"Critical":sap.ui.core.ValueState.Warning}[d]||sap.ui.core.ValueState.None;};t.bindItems("/THRESHOLDS",new sap.m.ObjectListItem({title:"{name}",number:"{value}",numberState:{path:"color",formatter:g}}));t.setModel(m);var b=this.jsonModel.getData().data;if(this.evaluationApi.getScaling()==-2){for(var e in b){if(b[e]){b[e].value=(b[e].value*100)+" %";}}}for(var j in b){a.THRESHOLDS.push({name:b[j].title,value:this.VALUE_FORMATTER.format(b[j].value),color:b[j].color});}m.setData(a);var c=new sap.m.Bar({contentMiddle:[new sap.m.Label({text:this.getModel("i18n").getProperty("DETAILS")})],contentRight:(jQuery.device.is.phone)?[]:[new sap.m.Button({icon:"sap-icon://decline",width:"2.375rem",press:jQuery.proxy(function(){if(this._CTpopOver.isOpen()){this._CTpopOver.close();}},this)})]});this._CTpopOver=new sap.m.ResponsivePopover({modal:false,enableScrolling:true,verticalScrolling:true,horizontalScrolling:false,placement:sap.m.PlacementType.Auto,contentWidth:"18rem",customHeader:c,content:[t]});var S=sap.ui.getCore().getUIArea(sap.ui.getCore().getStaticAreaRef());S.addContent(this._CTpopOver,true);};
