/*!
* SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2013 SAP SE. All rights reserved
* @deprecated since SAPUI 5 version 1.28.0
*/
jQuery.sap.declare("sap.suite.ui.smartbusiness.tiles.Numeric");jQuery.sap.require("sap.suite.ui.smartbusiness.tiles.Generic");sap.suite.ui.smartbusiness.tiles.Generic.extend("sap.suite.ui.smartbusiness.tiles.Numeric",{metadata:{properties:{kpiValueRequired:{type:"boolean",defaultValue:true},tileType:{type:"string",defaultValue:"NT"}}},renderer:{}});
sap.suite.ui.smartbusiness.tiles.Numeric.prototype.init=function(){sap.suite.ui.smartbusiness.tiles.Generic.prototype.init.apply(this);this.setAggregation("_tile",new sap.suite.ui.commons.GenericTile({header:"{/header}",subheader:"{/subheader}",size:this.getSize(),frameType:this.getFrameType(),tileContent:new sap.suite.ui.commons.TileContent({unit:"{/unit}",size:this.getSize(),footer:"{/footerNum}",content:new sap.suite.ui.commons.NumericContent({value:"{/value}",scale:"{/scale}",valueColor:"{/valueColor}",size:this.getSize(),state:"{/state}",formatterValue:true,truncateValueTo:5,nullifyValue:false})}),press:jQuery.proxy(this.tilePressed,this)}));this.jsonModel=new sap.ui.model.json.JSONModel();this.setModel(this.jsonModel);};
sap.suite.ui.smartbusiness.tiles.Numeric.prototype.onBeforeRendering=function(){sap.suite.ui.smartbusiness.tiles.Generic.prototype.onBeforeRendering.apply(this);if(this.getContentOnly()){this.setAggregation("_tile",new sap.suite.ui.commons.TileContent({unit:"{/unit}",size:this.getSize(),footer:"{/footerNum}",content:new sap.suite.ui.commons.NumericContent({value:"{/value}",scale:"{/scale}",valueColor:"{/valueColor}",size:this.getSize(),state:"{/state}",formatterValue:true,truncateValueTo:5,nullifyValue:false})}));}};
sap.suite.ui.smartbusiness.tiles.Numeric.prototype.switchOffFormatting=function(){try{this.getTileControl().getTileContent()[0].getContent().setFormatterValue(false);}catch(e){}};
sap.suite.ui.smartbusiness.tiles.Numeric.prototype.doProcess=function(){var n={};n.valueColor=this._applyTrendColor();n.indicator=this._applyTrendIndicator();n.frameType=this.getFrameType();n.unit=this.UOM;var s="";var c=this.KPI_VALUE;if(this.EVALUATION_DATA.SCALING==-2){n.formatterValue=false;}var i=this.isACurrencyMeasure(this.EVALUATION_DATA.COLUMN_NAME);var f=this.libFormat(c,i,this.UOM);if(this.EVALUATION_DATA.SCALING==-2){n.scale="%";this.switchOffFormatting();}if(f){n.value=f.toString();}else{n.value="0";}if(true||this.isAssociatedKpi()){n.header=this.EVALUATION_DATA.INDICATOR_TITLE;n.subheader=this.EVALUATION_DATA.TITLE;}this.jsonModel.setData(n);this.jsonModel.updateBindings();this.setDoneState();};
sap.suite.ui.smartbusiness.tiles.Numeric.prototype.doDummyProcess=function(){this.jsonModel.setData(this.getDummyDataForNumericTile());};
sap.suite.ui.smartbusiness.tiles.Numeric.prototype._applyTrendColor=function(){var r=null;var w=window.parseFloat(this.WARNING_LOW_VALUE);var c=window.parseFloat(this.CRITICAL_LOW_VALUE);var a=window.parseFloat(this.CRITICAL_HIGH_VALUE);var b=window.parseFloat(this.WARNING_HIGH_VALUE);var i=this.EVALUATION_DATA.GOAL_TYPE;if(this.evaluationApi.isMinimizingKpi()){if(this.hasSomeValue(a,b)){if(this.KPI_VALUE<b){r=sap.suite.ui.commons.InfoTileValueColor.Good;}else if(this.KPI_VALUE<=a){r=sap.suite.ui.commons.InfoTileValueColor.Critical;}else{r=sap.suite.ui.commons.InfoTileValueColor.Error;}}}else if(this.evaluationApi.isMaximizingKpi()){if(this.hasSomeValue(c,w)){if(this.KPI_VALUE<c){r=sap.suite.ui.commons.InfoTileValueColor.Error;}else if(this.KPI_VALUE<=w){r=sap.suite.ui.commons.InfoTileValueColor.Critical;}else{r=sap.suite.ui.commons.InfoTileValueColor.Good;}}}else{if(this.hasSomeValue(w,b,c,a)){if(this.KPI_VALUE<c||this.KPI_VALUE>a){r=sap.suite.ui.commons.InfoTileValueColor.Error;}else if((this.KPI_VALUE>=c&&this.KPI_VALUE<=w)||(this.KPI_VALUE>=b&&this.KPI_VALUE<=a)){r=sap.suite.ui.commons.InfoTileValueColor.Critical;}else{r=sap.suite.ui.commons.InfoTileValueColor.Good;}}}return r;};
sap.suite.ui.smartbusiness.tiles.Numeric.prototype._applyTrendIndicator=function(){var t=sap.suite.ui.commons.DeviationIndicator.None;if(this.TREND_VALUE||this.TREND_VALUE=="0"){if(this.TREND_VALUE>this.KPI_VALUE){t=sap.suite.ui.commons.DeviationIndicator.Down;}else if(this.TREND_VALUE<this.KPI_VALUE){t=sap.suite.ui.commons.DeviationIndicator.Up;}}return t;}
