jQuery.sap.declare("model.Description");

// Q: why are these text not in a property file?
// A: we do not want to translate the explored app for now.

model.Description = {
        facetOverview : "This control is used in UnifiedThingInspector to display the overview of the facet content along with the title and total number of items for the facet. It can be displayed on the desktop, tablet, and smartphone devices. You can set the height of the control using the heightType property. If it is set to Auto, the size of the control changes automatically according to the content. You can also define a fixed control height: XS, S, M, L, XL, or XXL. You can set the total number of items for the facet using the quantity property. The default value is -1. It means that the number of items is not displayed.",

        headerCell: "The Header Cell control displays one or more controls in different layouts. The controls are arranged and resized to fit in four regions: north, south, east, and west. Each aggregation must contain only one instance of HeaderCellItem.",
        headerContainer: "The Header Container control displays a set of controls in a horizontal strip. On mobile devices, this control is swipeable. On desktop, buttons are used to display the next or previous set of containers.",
        infoTile: "The Info Tile control displays the title, description, content area, and footer. You can insert any control into the content area. You can set up the size of the Info Tile using the size property. By default, the size property is set to Auto. It means that the size of the control changes automatically according to the device. You can also set a fixed control size: small (S), medium (M), or large (L). The first example displays the Info Tile of the large size in the Loaded status. The second example displays the Info Tile of the medium size in the Loading status. The third example displays the Info Tile of the small size that failed loading.",

        kpiTile: "This control is used in UnifiedThingInspector to display object-related key values in a factsheet. You can display the value in one of the two predefined font sizes using the doubleFontSize property. By default, this property is set to true. It means that the value is displayed using the 32px font size. This font size is convenient to use when the value is a number. If set to false, the value is displayed using the 16px font size. This font size is convenient to use when the value is a text. You can display the value in one of the predefined semantic colors using the valueStatus property. By default, this property is set to Neutral. You can also set one of the following semantic colors: Bad, Critical, or Good.",
        cmpTileFixed: "The Comparison Tile control is based on the Info Tile control and displays up to three values as bar charts along with the title, numeric value, and scaling factor in the content area. The tile content is displayed in semantic colors. The tile footer is not available. The unit of measure is displayed along with the tile description. You can either specify one of the predefined sizes (S, M, or L) of the Comparison Tile or set it to Auto so that it can automatically adjust to a device screen size. In the example above, a fixed control size is set.",
        cmpTileAuto: "This example shows the Comparison Tile control that resizes automatically to fit the size of the device since the size property is set to Auto by default.",
        bulletChart: "The Bullet Chart control displays an actual value as a horizontal bar in semantic color on the top of the background bar, the numeric value, the scaling factor, along with the thresholds, and a target value as vertical bars. You can either specify one of the predefined sizes (XS, S, M, or L) of the Bullet Chart or set the size property to Auto so that the control can automatically adjust to a device screen size.",
        linkActionSheet : "Similar to Action Sheet, Link Action Sheet displays a list of actions allowing you to select and perform an action. The main enhancement is that this control can contain not only buttons (sap.m.Button) but also links (sap.ui.commons.Link).",

        microAreaChart: "The Micro Area Chart control displays the history of values as a line mini chart or an area mini chart. It can display actual value and target value as segmented lines and thresholds as semantically colored background area. If the thresholds are not defined, the background remains transparent, so that only actual and target lines are displayed (if defined). This control also allows you to display or hide the labels for the start and end dates, start and end values and the min and max values, if defined. It is possible to set the fixed horizontal and vertical scales.",
        monitoringTile: "The Monitoring Tile control displays the title, description, content area, and footer. This control is used to display a numeric value and an icon into the content area. You can set up the size of the Monitoring Tile using the size property. By default, the size property is set to Auto. It means that the size of the control changes automatically according to the device. You can also set a fixed control size: small (S), medium (M), or large (L).",

        numericTileDifferentSizes: "The Numeric Tile displays the same items as the Info Tile control but the content area contains numbers, number units, and state arrows. The numbers can be displayed in semantic colors. You can set up the size of the Numeric Tile. By default, the size property is set to Auto. It means that the size of the control changes automatically according to the device. You can also set a fixed control size: small (S), medium (M), or large (L).",
        numericTileLoading: "This is an example of the Numeric Tile in the Loading status.",
        numericTileFailed: "This is an example of the Numeric Tile that failed loading.",
        
        unifiedThingInspector : "This control is used to display the object-related factsheets on the desktops, tablets, and smartphones.",
        unifiedThingInspectorFacet : "In this example, the header area contains the object image, condensed object header, and two key values represented by the KpiTile controls. The content area contains teaser tiles represented by the FacetOverview controls. Depending on the device type and orientation, the layout changes respectively. The footer area contains the configuration icon, the Open In menu represented by the LinkActionSheet control, and the Actions menu represented by the ActionSheet control.",
        
        numericContentDifferentSizes : "NumericContent contains numbers, number units, an icon, and state arrows. The numbers can be displayed in semantic colors. You can set up the size of the NumericContent. By default, the size property is set to Auto. It means that the size of the control changes automatically according to the device. You can also set a fixed control size: small (S), medium (M), or large (L).",
        numericContentLoading: "This is an example of the NumericContent in the Loading status.",
        numericContentFailed: "This is an example of the NumericContent that failed loading.",
        numericContentIcon: "This is an example of the NumericContent that contains an icon.",
        
        monitoringContent: "This control is used to display a numeric value and an icon into the content area. You can set up the size of the Monitoring Content using the size property. By default, the size property is set to Auto. It means that the size of the control changes automatically according to the device. You can also set a fixed control size: small (S), medium (M), or large (L).",
        comparisonChart: "The Comparison Chart control displays up to three values as bar charts along with the title, numeric value, and scaling factor in the content area. The chart content is displayed in semantic colors. You can either specify one of the predefined sizes (S, M, or L) of the Comparison Chart or set the size property to Auto so that the control can automatically adjust to a device screen size.",
        chartTile: "The Chart Tile control displays the title, description, content area, and footer. You can insert Bullet Chart or Comparison Chart into the content area. You can either specify one of the predefined sizes (S, M, or L) of the Chart Tile or set the size property to Auto so that the control can automatically adjust to a device screen size."
};