/*!
 * SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2014 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.collaboration.components.socialtimeline.controls.TimelineEntryControl");jQuery.sap.require("sap.collaboration.components.utils.CommonUtil");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.collaboration.components.socialtimeline.controls.TimelineEntryControl",{metadata:{publicMethods:[],library:"sap.collaboration",properties:{"timelineEntry":{type:"object",group:"data"}},aggregations:{}}});
sap.collaboration.components.socialtimeline.controls.TimelineEntryControl.prototype.init=function(){this._oCommonUtil=new sap.collaboration.components.utils.CommonUtil();this._oLangBundle=this._oCommonUtil.getLanguageBundle();};
sap.collaboration.components.socialtimeline.controls.TimelineEntryControl.prototype.onBeforeRendering=function(){if(!this._oFlexbox){this._oFlexbox=new sap.m.FlexBox(this.getId()+"_flexbox",{direction:"Column"});this._fillFlexbox();}};
sap.collaboration.components.socialtimeline.controls.TimelineEntryControl.prototype.exit=function(){if(this._oFlexbox){this._oFlexbox.destroy();if(this._oPopover){this._oPopover.destroy();}}};
sap.collaboration.components.socialtimeline.controls.TimelineEntryControl.prototype._fillFlexbox=function(){var t=this.getTimelineEntry();if(t.timelineEntryDetails!=undefined&&t.timelineEntryDetails.length>0){var f=this._parseTimelineEntryDetail(t.timelineEntryDetails[0]);this._oFlexbox.addItem(new sap.m.Text({text:f}));if(t.timelineEntryDetails.length>1){var l=this._createLink(t.timelineEntryDetails);this._oFlexbox.addItem(l);}}else{this._oFlexbox.addItem(new sap.m.Text({text:t.text}));}};
sap.collaboration.components.socialtimeline.controls.TimelineEntryControl.prototype._createLink=function(t){var s=this;var a=t.length-1;var l=new sap.m.Link(this.getId()+"_PopoverLink",{text:this._oLangBundle.getText("TE_LINK_TEXT",a)});l.attachPress(function(){if(!s._oPopover){s._oPopover=s._createPopover(t);}s._oPopover.openBy(l);});return l;};
sap.collaboration.components.socialtimeline.controls.TimelineEntryControl.prototype._createPopover=function(t){var c=new sap.m.List(this.getId()+"_ChangeList",{inset:false});for(var e in t){var E=this._parseTimelineEntryDetail(t[e]);var l=new sap.m.FeedListItem({text:E,showIcon:false});c.addItem(l);}var S="20em";var p=new sap.m.Popover(this.getId()+"_Popover",{contentWidth:S,placement:sap.m.PlacementType.Auto,title:this._oLangBundle.getText("TE_DETAILS_POPOVER_HEADER")+"("+t.length+")",content:[c]});return p;};
sap.collaboration.components.socialtimeline.controls.TimelineEntryControl.prototype._parseTimelineEntryDetail=function(d){var t="";switch(d.changeType){case"U":t=this._oLangBundle.getText("TE_DETAILS_CHANGED",[d.propertyLabel,d.beforeValue,d.afterValue]);break;case"I":t=this._oLangBundle.getText("TE_DETAILS_SET",[d.propertyLabel,d.afterValue]);break;case"D":t=this._oLangBundle.getText("TE_DETAILS_CLEARED",[d.propertyLabel,d.beforeValue]);break;}return t;};
