/*!
* SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2013 SAP SE. All rights reserved
* @deprecated since SAPUI 5 version 1.28.0
*/
jQuery.sap.declare("sap.suite.ui.smartbusiness.lib.Filter");sap.ui.core.Control.extend("sap.suite.ui.smartbusiness.lib.Filter",{metadata:{properties:{evaluationId:"string",dimensions:{type:"any",defaultValue:[]},visible:{type:"boolean",defaultValue:true},advancedSetting:{type:"object",defaultValue:{}},mode:{type:"string",defaultValue:"Runtime"},suppressAction:{type:"boolean",defaultValue:false},sapSystem:{type:"string",defaultValue:null}},aggregations:{"_filter":{type:"sap.ui.core.Control",multiple:false,visibility:"hidden"},"_popover":{type:"sap.m.Popover",multiple:false,visibility:"hidden"}},events:{filterChange:{}}},renderer:function(r,c){r.write("<div");r.writeControlData(c);r.addClass("SmartBusinessFilter");r.writeClasses();r.write(">");r.renderControl(c.getAggregation("_filter"));r.write("</div>");}});
sap.suite.ui.smartbusiness.lib.Filter.prototype.init=function(){this._filterObj={};if(sap.ushell&&sap.ushell.Container){this.urlParsingService=sap.ushell.Container.getService("URLParsing");}else{this.urlParsingService=undefined;}};
sap.suite.ui.smartbusiness.lib.Filter.prototype.onBeforeRendering=function(){if(this.getEvaluationId()){try{this._updateOdataProperties();this._facetListsReference={};var c=this._getChildControl();c.setVisible(this.getVisible());this.setAggregation("_filter",c);this._initModel();if(this.getMode()=="Runtime"){this._addDimensions(this.getDimensions());}else{this._addDimensionsDesignTime(this.getDimensions());}}catch(e){jQuery.sap.log.error(e);}}};
sap.suite.ui.smartbusiness.lib.Filter.prototype.onAfterRendering=function(){if(this.getMode()=="Runtime"){this.refreshFilter(true);}};
sap.suite.ui.smartbusiness.lib.Filter.prototype.getFacetFilterReference=function(){return this.getAggregation("_filter");};
sap.suite.ui.smartbusiness.lib.Filter.prototype.getSelectedItems=function(){var f=this.getAggregation("_filter");var l=f.getLists();var c=0;for(var i=0;i<l.length;i++){if(l[i].getSelectedItems().length>0){c++;}}if(c>0){return true;}else{return false;}};
sap.suite.ui.smartbusiness.lib.Filter.prototype._updateOdataProperties=function(){if(this.urlParsingService){this._serviceUri=this.urlParsingService.addSystemToServiceUrl(this.EVALUATION.getODataUrl(),this.getSapSystem());}else{this._serviceUri=this.EVALUATION.getODataUrl();}this._entitySet=this.EVALUATION.getEntitySet();};
sap.suite.ui.smartbusiness.lib.Filter.prototype._getChildControl=function(){var c,t=this;function _(C,w){return new sap.m.HBox({items:C,width:w})}if(this.getMode()=="Runtime"){c=new sap.m.FacetFilter({showReset:false,showPersonalization:true,showPopoverOKButton:true,reset:jQuery.proxy(function(){t.resetFilter.call(this);},this)});}else{this._facetContainer=new sap.m.ScrollContainer({vertical:false,horizontal:true,}).addStyleClass("facetFilterContainer");c=new sap.m.HBox({justifyContent:"SpaceBetween",alignItems:"Center",items:[_([this._facetContainer]),_([new sap.m.Button({icon:"sap-icon://undo",type:"Transparent",visible:(!t.getSuppressAction()),press:function(){if(!t.getSuppressAction()){t.rerender();}}}),new sap.m.Button({icon:((!t.getSuppressAction())?"sap-icon://add-filter":"sap-icon://filter"),type:"Transparent",enabled:((!t.getSuppressAction())?true:false),press:function(){if(!t.getSuppressAction()){t._popover.openBy(this);}}})])]});}return c;};
sap.suite.ui.smartbusiness.lib.Filter.prototype.resetFilter=function(){this._filterObj=sap.suite.ui.smartbusiness.drilldown.lib.Hash.getApplicationParameters();var v=sap.suite.ui.smartbusiness.drilldown.lib.Hash.getApplicationParameters().viewId[0];var n={viewId:[v]};var t=this;var d=sap.suite.ui.smartbusiness.lib.Util.odata.getAllFilterableDimensions(this._serviceUri,this._entitySet);d.forEach(function(s){delete t._filterObj[s];});for(var e in this._filterObj){n[e]=this._filterObj[e];}sap.suite.ui.smartbusiness.drilldown.lib.Hash.setApplicationParameters(n);this.rerender();};
sap.suite.ui.smartbusiness.lib.Filter.prototype._addDimensions=function(d){var c=[];if(d&&d.length){if(typeof d=='string'){d=d.split(",");}}if(this.getEvaluationId()){var f=sap.suite.ui.smartbusiness.lib.Util.odata.getAllFilterableDimensions(this._serviceUri,this._entitySet);}for(var i=0;i<d.length;i++){c.push({name:d[i],isDelta:false});}for(var i=0;i<f.length;i++){if(d.indexOf(f[i])==-1)c.push({name:f[i],isDelta:true});}var p=sap.suite.ui.smartbusiness.lib.Util.odata.properties(this._serviceUri,this._entitySet);var C=p.getLabelMappingObject();try{c.sort(function(a,b){return C[a.name]>C[b.name]?1:-1;});}catch(e){jQuery.sap.log.error(e);}for(var i=0;i<c.length;i++){this.addFacetList(c[i].name,c[i].isDelta,p);}};
sap.suite.ui.smartbusiness.lib.Filter.prototype.facetListClosed=function(e){this.fireFilterChange(e);};
sap.suite.ui.smartbusiness.lib.Filter.prototype.setEvaluationData=function(e){this.EVALUATION=e;};
sap.suite.ui.smartbusiness.lib.Filter.prototype.getSelectedKeys=function(l){var s=[];if(l.getActive()){var a=l.getSelectedItems();for(var i=0;i<a.length;i++){if(a[i].getSelected()){var v=a[i].getKey();var b=(v||v==0)?v:(v==null)?"SAP_SMARTBUSINESS_NULL":"";b=b.getTime?b.getTime():b;s.push(b+"");}}}return s;};
sap.suite.ui.smartbusiness.lib.Filter.prototype.addFacetList=function(f,i,p){var t=this;var a=this.getAggregation("_filter");var C=p.getLabelMappingObject();var T=p.getTextPropertyMappingObject();var b=new sap.m.FacetFilterList({key:f,title:C[f],displaySecondaryValues:true,growingThreshold:999,active:!i,listOpen:function(){t._fetchListData(this);}});this._facetListsReference[f]=b;b._techName=f;b._isDelta=i;b._isFilterDirty=true;b._prevSelectedKeys=[];if(this.getMode()=="Runtime"){b.attachListClose(function(){var c=sap.suite.ui.smartbusiness.drilldown.lib.Hash.getApplicationParameters(['viewId']);this._prevSelectedKeys=c[this._techName]||[];if(JSON.stringify(this._prevSelectedKeys)!=JSON.stringify(t.getSelectedKeys(this))){this._prevSelectedKeys=t.getSelectedKeys(this);t._setFilterDirty(this.getKey());t._updateFilter(this.getKey(),this._prevSelectedKeys);}if(!this.getActive()){this._isFilterDirty=true}});}b.bindAggregation("items","/",new sap.m.FacetFilterItem({key:{path:f},text:{formatter:t._getColumnValueFormatter(T[f]),path:T[f]}})).setModel(new sap.ui.model.json.JSONModel());a.addList(b);};
sap.suite.ui.smartbusiness.lib.Filter.prototype.refreshFilter=function(n){if(this.getVisible()){var p=this._filterObj||{};var i=false;try{var f=this._facetListsReference;if(f&&this.getMode()=="Runtime"){this._filterObj=sap.suite.ui.smartbusiness.drilldown.lib.Hash.getApplicationParameters(["viewId"]);for(var a in this._filterObj){if(((p[a]+"")!=(this._filterObj[a]+""))||(this._filterObj[a]+""&&!f[a].getActive())){f[a].setActive(true);f[a]._isSelectionChanged=true;i=true;}}for(var a in p){if(((p[a]+"")!=(this._filterObj[a]+""))||(p[a]+""&&!f[a].getActive())){f[a].setActive(true);f[a]._isSelectionChanged=true;i=true;}}n=!!n;if(this.getAggregation("_filter")&&!n){}}var b=this.getAggregation("_filter");if(b&&i){var c=sap.suite.ui.smartbusiness.drilldown.lib.Hash.getApplicationParameters(["viewId"]);for(var a in f){if(f[a]._isSelectionChanged){this.updateSelections(f[a],c[a]||[]);}}}}catch(e){jQuery.sap.log.error(e);}}};
sap.suite.ui.smartbusiness.lib.Filter.prototype.updateSelections=function(f,s){var a=f.getModel().getData();if(!(a instanceof Array)||!a.length){if(s.length==1){f._isFilterDirty=true;this._fetchListData(f);}else{this._fetchPseudoListData(f,s);f._isFilterDirty=true;}}else{this._retainListSelections(f);}};
sap.suite.ui.smartbusiness.lib.Filter.prototype._updateFilter=function(d,f){this._filterObj=sap.suite.ui.smartbusiness.drilldown.lib.Hash.getApplicationParameters();var v=sap.suite.ui.smartbusiness.drilldown.lib.Hash.getApplicationParameters().viewId[0];var n={viewId:[v]};if(f.length){this._filterObj[d]=f;}else{delete this._filterObj[d];}for(var e in this._filterObj){n[e]=this._filterObj[e];}sap.suite.ui.smartbusiness.drilldown.lib.Hash.setApplicationParameters(n);};
sap.suite.ui.smartbusiness.lib.Filter.prototype._getValidFilters=function(d){var o=[];var f=sap.suite.ui.smartbusiness.drilldown.lib.Hash.getApplicationParameters(["viewId",d]);for(var e in f){var a=f[e];if(a&&a.length){a.forEach(function(F){o.push({NAME:e,VALUE_1:F,VALUE_2:"",TYPE:"FI",OPERATOR:"EQ"});});}}return o;};
sap.suite.ui.smartbusiness.lib.Filter.prototype.getActiveDimensions=function(){var t=[];if(this.getMode()=="RunTime"){var f=this.getAggregation("_filter").getLists();f.forEach(function(s){if(s.getActive()){t.push(s._techName);}});}else{var l=this._designTimeModel.getProperty("/");l.forEach(function(s){if(s.selected){t.push(s.name);}});}return t;};
sap.suite.ui.smartbusiness.lib.Filter.prototype._retainListSelections=function(l){if(this.getMode()=="Runtime"){this._filterObj=sap.suite.ui.smartbusiness.drilldown.lib.Hash.getApplicationParameters(["viewId"]);var c=this._filterObj[l.getKey()]||[];for(var i=0,a=l.getItems();i<a.length;i++){var b=a[i].getBindingContext().getObject()[l._techName];b=(b==null)?"SAP_SMARTBUSINESS_NULL":(b||b==0?b:"");b=b.getTime?b.getTime()+"":b+"";a[i].setSelected(c.indexOf(b)!=-1);}l._isSelectionChanged=false;}};
sap.suite.ui.smartbusiness.lib.Filter.prototype._getFilterString=function(d,o){return sap.suite.ui.smartbusiness.lib.Util.odata.getUri({entitySet:this._entitySet,serviceUri:this._serviceUri,dimension:d,filter:o.concat(this.EVALUATION.getFilters().results)}).uri;};
sap.suite.ui.smartbusiness.lib.Filter.prototype._setFilterDirty=function(e){var f=this.getAggregation("_filter");for(var i=0,l=f.getLists();i<l.length;i++){if(l[i].getKey()!=e){l[i]._isFilterDirty=true;}}};
sap.suite.ui.smartbusiness.lib.Filter.prototype._onAfterListDataFetch=function(l,d){l.getModel().setData(d);this._retainListSelections(l);l._isFilterDirty=false;l.setBusy(false);};
sap.suite.ui.smartbusiness.lib.Filter.prototype._fetchPseudoListData=function(l,p){var d=[];var a=l.getKey();for(var e in p){var o={};o[a]=p[e];d.push(o);}this._onAfterListDataFetch(l,d);};
sap.suite.ui.smartbusiness.lib.Filter.prototype._fetchListData=function(l,f){if(l._isFilterDirty){var t=this;if(this.getMode()=="Runtime"){l.setBusy(true);this.oDataModel.read(this._getFilterString(l.getKey(),this._getValidFilters(l.getKey())),null,null,true,function(d){t._onAfterListDataFetch(l,d.results);},function(){});}}else if(l._isSelectionChanged){this._retainListSelections(l);}};
sap.suite.ui.smartbusiness.lib.Filter.prototype._initModel=function(){if(this.getEvaluationId()){if(sap.suite.ui.smartbusiness.lib.Util.odata){this.oDataModel=sap.suite.ui.smartbusiness.lib.Util.odata.getModelByServiceUri(this._serviceUri);}else{this.oDataModel=new sap.ui.model.odata.ODataModel(this._serviceUri,true);}}};
sap.suite.ui.smartbusiness.lib.Filter.prototype._getColumnValueFormatter=function(n){var f=function(s){return s==0?s+"":s;};var m=sap.suite.ui.smartbusiness.lib.Util.odata.getEdmType(this._serviceUri,n,true);var t=m.type;var F=m.format.toUpperCase();if(t=='Edm.DateTime'){if(!sap.suite.ui.smartbusiness.lib.Util.odata.isTimeZoneIndependent(this._serviceUri,this._entitySet)){var a;if(F=="DATE"||F=="NONE"){a="daysAgo";}else if(F=="DATETIME"){a="";}if(a){var o=new sap.ca.ui.model.type.Date({style:a});f=function(s){return o.formatValue(s,"string");}}else{var o=sap.ui.core.format.DateFormat.getDateTimeInstance();f=function(b){if(b&&b.getMinutes){return o.format(b);}return b;}}}else{f=function(b){if(b&&b.getMinutes){b=new Date(b.getTime());b.setMinutes(b.getMinutes()+b.getTimezoneOffset());var i=(F=="DATE")?"getDateInstance":"getDateTimeInstance";return sap.ui.core.format.DateFormat[i]().format(b);}return b;}}}return f;};
sap.suite.ui.smartbusiness.lib.Filter.prototype._getDesignTimeModel=function(a){var d=[];a=a||[];var p=sap.suite.ui.smartbusiness.lib.Util.odata.properties(this._serviceUri,this._entitySet);var C=p.getLabelMappingObject();var b=sap.suite.ui.smartbusiness.lib.Util.odata.getAllFilterableDimensions(this._serviceUri,this._entitySet);if(a&&a.length){if(typeof a=='string'){a=a.split(",");}}b.forEach(function(s){d.push({name:s,label:C[s],selected:a.indexOf(s)!=-1});});return new sap.ui.model.json.JSONModel(d);};
sap.suite.ui.smartbusiness.lib.Filter.prototype._addDimensionsDesignTime=function(d){function o(e){var c=[];var q=e.getSource().getValue();var g=p.getBinding("items");if(q&&q.length>0){c=[new sap.ui.model.Filter("label",sap.ui.model.FilterOperator.Contains,q)]}g.filter(c);}this._designTimeModel=this._getDesignTimeModel(d);this._designTimeModel.setSizeLimit(999);this._facetContainer.setModel(this._designTimeModel);var p=new sap.m.List({mode:"MultiSelect"});var s=new sap.m.SearchField({width:"100%",liveChange:jQuery.proxy(o,this)});this._popover=new sap.m.Popover({customHeader:s,content:[p],showHeader:false,placement:"Bottom"});this._popover.setModel(this._designTimeModel);var a=new sap.ui.model.Sorter('label',false);p.bindAggregation("items",{path:"/",template:new sap.m.StandardListItem({title:"{label}",selected:"{selected}"}),sorter:a});var f=new sap.m.HBox({visible:"{selected}",justifyContent:"SpaceBetween",items:[new sap.m.Label({text:"{label}"}).addStyleClass("dimensionName"),new sap.ui.core.Icon({src:"sap-icon://sys-cancel",visible:!this.getSuppressAction(),press:function(){this.getParent().setVisible(false);}})]}).addStyleClass("facetFilterDimension");var b=new sap.m.HBox();b.bindAggregation("items","/",f);this._facetContainer.addContent(b);};
